import { AlbumBook, AlbumPage } from '../types';

export const INITIAL_ALBUM: AlbumBook = {
  id: 'memory-album-2024',
  title: 'Chapters of Life',
  subtitle: 'A Collection of Cherished Memories & Wanderlust',
  author: 'Our Story',
  coverColor: 'leather-brown',
  goldEmbossing: true,
  updatedAt: new Date().toISOString(),
  pages: [
    // Page 1: Cover inside / Intro page
    {
      id: 'page-intro',
      pageNumber: 1,
      title: 'The Golden Coast Journey',
      subtitle: 'Summer Roadtrip & Coastal Breezes',
      journalNotes: 'We started our engines just before dawn. The Pacific salt air was brisk, and with a trunk full of memories in the making, every mile felt like pure freedom.',
      layout: 'single-hero',
      photos: [
        {
          id: 'p-coast-1',
          url: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1200&q=80',
          caption: 'Golden hour waves rolling onto the sand',
          date: 'July 14, 2024',
          location: 'Big Sur, California',
          frameStyle: 'polaroid',
          filter: 'warm',
          rotation: -2,
          tapeStyle: 'washi-gold',
        },
      ],
      stickers: [
        { id: 's1', type: 'camera', x: 82, y: 15, rotation: 12, scale: 1 },
        { id: 's2', type: 'sparkle', x: 12, y: 78, rotation: -8, scale: 0.9 },
      ],
      style: {
        fontFamily: 'Playfair Display',
        fontSize: 'base',
        titleColor: '#3c2415',
        bodyColor: '#5c4533',
        paperTexture: 'parchment',
        titleAlignment: 'center',
        showPageNumber: true,
        ornamentStyle: 'botanical',
      },
    },

    // Page 2: Double Polaroid Snapshots
    {
      id: 'page-polaroids',
      pageNumber: 2,
      title: 'Little Moments of Joy',
      subtitle: 'Espresso & Slow Sunday Mornings',
      journalNotes: 'Finding that cozy corner bakery tucked inside the cobblestone alley. Fresh almond croissants and warm lattes while the world slowly woke up.',
      layout: 'polaroid-duo',
      photos: [
        {
          id: 'p-coffee-1',
          url: 'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?auto=format&fit=crop&w=800&q=80',
          caption: 'Morning brew at the hidden courtyard cafe',
          date: 'Aug 03, 2024',
          location: 'Old Town Square',
          frameStyle: 'polaroid',
          filter: 'vintage',
          rotation: -3,
          tapeStyle: 'washi-pink',
        },
        {
          id: 'p-coffee-2',
          url: 'https://images.unsplash.com/photo-1501339847302-ac426a4a7cbb?auto=format&fit=crop&w=800&q=80',
          caption: 'Steam rising in the morning light',
          date: 'Aug 03, 2024',
          location: 'Rue des Fleurs',
          frameStyle: 'polaroid',
          filter: 'warm',
          rotation: 4,
          tapeStyle: 'kraft-tape',
        },
      ],
      stickers: [
        { id: 's-coffee', type: 'coffee', x: 88, y: 82, rotation: -6, scale: 1 },
        { id: 's-heart', type: 'heart', x: 8, y: 18, rotation: 10, scale: 0.9 },
      ],
      style: {
        fontFamily: 'Caveat',
        fontSize: 'lg',
        titleColor: '#2d1808',
        bodyColor: '#4a2f1b',
        paperTexture: 'linen',
        titleAlignment: 'left',
        showPageNumber: true,
        ornamentStyle: 'vintage-flourish',
      },
    },

    // Page 3: Mountain Getaway Triple Story
    {
      id: 'page-mountains',
      pageNumber: 3,
      title: 'Whispering Pine Summits',
      subtitle: 'Hiking High Above the Clouds',
      journalNotes: 'The four-hour trek tested our legs, but reaching the alpine lake at 9,000 feet made every step worth it. Crystal turquoise waters reflected the snow-dusted peaks.',
      layout: 'triple-story',
      photos: [
        {
          id: 'p-mount-1',
          url: 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=800&q=80',
          caption: 'First light touching the summit peaks',
          date: 'Sept 18, 2024',
          location: 'Alpine Pass',
          frameStyle: 'golden-border',
          filter: 'vivid',
          rotation: 0,
          tapeStyle: 'none',
        },
        {
          id: 'p-mount-2',
          url: 'https://images.unsplash.com/photo-1486870591958-9b9d0d1dda99?auto=format&fit=crop&w=800&q=80',
          caption: 'Reflections on the tranquil mirrored lake',
          date: 'Sept 18, 2024',
          location: 'Mirror Basin',
          frameStyle: 'vintage-tape',
          filter: 'cool',
          rotation: -2,
          tapeStyle: 'washi-teal',
        },
        {
          id: 'p-mount-3',
          url: 'https://images.unsplash.com/photo-1519681393784-d120267933ba?auto=format&fit=crop&w=800&q=80',
          caption: 'Stargazing under the crystal clear night sky',
          date: 'Sept 19, 2024',
          location: 'Timberline Camp',
          frameStyle: 'vintage-tape',
          filter: 'none',
          rotation: 3,
          tapeStyle: 'washi-gold',
        },
      ],
      stickers: [
        { id: 's-star', type: 'star', x: 85, y: 12, rotation: 15, scale: 1 },
        { id: 's-pin', type: 'pin', x: 14, y: 88, rotation: -12, scale: 1 },
      ],
      style: {
        fontFamily: 'Cinzel',
        fontSize: 'base',
        titleColor: '#1e293b',
        bodyColor: '#334155',
        paperTexture: 'kraft',
        titleAlignment: 'left',
        showPageNumber: true,
        ornamentStyle: 'minimal-line',
      },
    },

    // Page 4: 4-Photo Scrapbook Grid
    {
      id: 'page-scrapbook',
      pageNumber: 4,
      title: 'City Lights & Architecture',
      subtitle: 'Snapshots from Our European Odyssey',
      journalNotes: 'Every corner had a story to tell. Centuries-old stone bridges, antique bookstores, bustling evening bistros, and vintage trams rattling down the avenue.',
      layout: 'quad-scrapbook',
      photos: [
        {
          id: 'p-city-1',
          url: 'https://images.unsplash.com/photo-1513635269975-59663e0ac1ad?auto=format&fit=crop&w=600&q=80',
          caption: 'Historic London clocktower',
          date: 'Oct 02, 2024',
          location: 'Westminster',
          frameStyle: 'filmstrip',
          filter: 'vintage',
          rotation: -1,
          tapeStyle: 'none',
        },
        {
          id: 'p-city-2',
          url: 'https://images.unsplash.com/photo-1502602898657-3e91760cbb34?auto=format&fit=crop&w=600&q=80',
          caption: 'Eiffel Tower autumn glow',
          date: 'Oct 05, 2024',
          location: 'Champ de Mars',
          frameStyle: 'polaroid',
          filter: 'warm',
          rotation: 2,
          tapeStyle: 'washi-pink',
        },
        {
          id: 'p-city-3',
          url: 'https://images.unsplash.com/photo-1534447677768-be436bb09401?auto=format&fit=crop&w=600&q=80',
          caption: 'Cobblestone streets & red bicycles',
          date: 'Oct 08, 2024',
          location: 'Amsterdam Canal',
          frameStyle: 'vintage-tape',
          filter: 'sepia',
          rotation: -2,
          tapeStyle: 'washi-gold',
        },
        {
          id: 'p-city-4',
          url: 'https://images.unsplash.com/photo-1520939817895-060bdef4dc1b?auto=format&fit=crop&w=600&q=80',
          caption: 'Venice gondola glides at dusk',
          date: 'Oct 11, 2024',
          location: 'Grand Canal',
          frameStyle: 'polaroid',
          filter: 'warm',
          rotation: 3,
          tapeStyle: 'kraft-tape',
        },
      ],
      stickers: [
        { id: 's-plane', type: 'plane', x: 88, y: 14, rotation: -15, scale: 1 },
        { id: 's-stamp', type: 'stamp', x: 10, y: 88, rotation: 8, scale: 1.1 },
      ],
      style: {
        fontFamily: 'Courier Prime',
        fontSize: 'base',
        titleColor: '#2b231c',
        bodyColor: '#4d4035',
        paperTexture: 'parchment',
        titleAlignment: 'center',
        showPageNumber: true,
        ornamentStyle: 'vintage-flourish',
      },
    },

    // Page 5: Journal & Heartfelt Note
    {
      id: 'page-journal',
      pageNumber: 5,
      title: 'A Letter to the Days Ahead',
      subtitle: 'Reflections & Gratitude',
      journalNotes: 'Years from now, when we open this book, we will remember not just the sights we saw, but how the wind felt against our faces, the spontaneous laughter in rainy cafes, and the peace of simply being present with one another. Life is made of these quiet, glowing fragments.',
      layout: 'journal-photo',
      photos: [
        {
          id: 'p-flower-1',
          url: 'https://images.unsplash.com/photo-1490750967868-88aa4486c946?auto=format&fit=crop&w=800&q=80',
          caption: 'Wildflowers pressed between pages of our thoughts',
          date: 'November 2024',
          location: 'Meadow Hill',
          frameStyle: 'stamp-border',
          filter: 'warm',
          rotation: -3,
          tapeStyle: 'washi-gold',
        },
      ],
      stickers: [
        { id: 's-flower', type: 'flower', x: 82, y: 82, rotation: 20, scale: 1.2 },
        { id: 's-heart2', type: 'heart', x: 14, y: 15, rotation: -8, scale: 0.9 },
      ],
      style: {
        fontFamily: 'Dancing Script',
        fontSize: 'lg',
        titleColor: '#3a2012',
        bodyColor: '#523420',
        paperTexture: 'vintage-floral',
        titleAlignment: 'center',
        showPageNumber: true,
        ornamentStyle: 'botanical',
      },
    },

    // Page 6: Golden Sunset Farewell
    {
      id: 'page-sunset',
      pageNumber: 6,
      title: 'Endless Horizons',
      subtitle: 'To the Next Chapter...',
      journalNotes: 'The sun sets on this chapter, only to rise on the next adventure waiting to be written. Keep wandering, keep loving, and keep capturing every fleeting spark.',
      layout: 'single-hero',
      photos: [
        {
          id: 'p-sunset-1',
          url: 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=1200&q=80',
          caption: 'Yosemite valley illuminated in sunset fire',
          date: 'December 2024',
          location: 'Glacier Point',
          frameStyle: 'golden-border',
          filter: 'warm',
          rotation: 0,
          tapeStyle: 'none',
        },
      ],
      stickers: [
        { id: 's-sparkle2', type: 'sparkle', x: 88, y: 18, rotation: 0, scale: 1 },
        { id: 's-quote', type: 'quote', x: 12, y: 86, rotation: 5, scale: 1 },
      ],
      style: {
        fontFamily: 'Playfair Display',
        fontSize: 'base',
        titleColor: '#3b2110',
        bodyColor: '#5c3920',
        paperTexture: 'parchment',
        titleAlignment: 'center',
        showPageNumber: true,
        ornamentStyle: 'botanical',
      },
    },
  ],
};

export const createNewPage = (pageNumber: number, layout: AlbumPage['layout'] = 'polaroid-duo'): AlbumPage => {
  return {
    id: 'page-' + Date.now() + '-' + Math.random().toString(36).substr(2, 6),
    pageNumber,
    title: 'New Memory Chapter',
    subtitle: 'Date & Location',
    journalNotes: 'Click here or in the editor toolbar to write your heartfelt thoughts, quotes, or story notes for this page...',
    layout,
    photos: [
      {
        id: 'photo-' + Date.now() + '-1',
        url: '',
        caption: 'Add a memorable caption...',
        date: new Date().toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' }),
        location: 'Your Location',
        frameStyle: 'polaroid',
        filter: 'none',
        rotation: (Math.random() * 4) - 2,
        tapeStyle: 'washi-gold',
      },
    ],
    stickers: [],
    style: {
      fontFamily: 'Playfair Display',
      fontSize: 'base',
      titleColor: '#2b1d0c',
      bodyColor: '#4a3825',
      paperTexture: 'parchment',
      titleAlignment: 'center',
      showPageNumber: true,
      ornamentStyle: 'botanical',
    },
  };
};
