// scripts/add_more_places.js
const fs = require('fs');
const path = require('path');

const placesPath = path.join(__dirname, '..', 'banglapath-home', 'places.json');
const currentData = JSON.parse(fs.readFileSync(placesPath, 'utf8'));

const MORE_PLACES = [
  // Additional gems across Bangladesh:
  {
    id: "sandwip",
    name: "Sandwip Ancient Island",
    district: "Chattogram",
    division: "Chattogram",
    tag: "Historic Estuary Island",
    icon: "beach",
    rating: 4.5,
    reviews: "3.4K+",
    blurb: "3,000-year-old historic delta island in the Meghna estuary.",
    image: "images/places/coxsbazar-3.jpg",
    facts: "One of the oldest populated islands of Bengal, historic hub of salt trade and wooden shipbuilding.",
    lat: 22.4833,
    lon: 91.4333,
    travel: "Water",
    fareLabel: "Sea Truck / Speedboat",
    fare: "৳250 – ৳500",
    season: "Oct – Mar",
    distance: "18 km sea",
    distanceFrom: "from Kumira Ghat, Chattogram",
    about: "Sandwip carries thousands of years of sea-faring history. The western coast boasts vast green embankment pastures where buffalo herds graze against golden sunset tides.",
    gallery: ["images/places/coxsbazar-3.jpg", "images/places/inani.jpg", "images/places/saintmartin.jpg"]
  },
  {
    id: "tinbigha",
    name: "Tin Bigha Corridor",
    district: "Lalmonirhat",
    division: "Rangpur",
    tag: "Historical Enclave",
    icon: "landmark",
    rating: 4.5,
    reviews: "4.1K+",
    blurb: "Historic border corridor connecting the Dahagram-Angarpota enclave.",
    image: "images/places/sonargaon-2.jpg",
    facts: "Symbolic strip of land leased to Bangladesh in 1992, allowing continuous passage to the enclave.",
    lat: 26.2500,
    lon: 88.9500,
    travel: "Road",
    fareLabel: "Bus Fare",
    fare: "৳80 – ৳200",
    season: "Oct – Mar",
    distance: "65 km",
    distanceFrom: "from Lalmonirhat town",
    about: "A place steeped in geopolitical history. Border flags, tranquil rural paddy fields, and friendly local communities offer a touching look into borderland life.",
    gallery: ["images/places/sonargaon-2.jpg", "images/places/lalbagh.jpg", "images/places/paharpur.jpg"]
  },
  {
    id: "teesta_barrage",
    name: "Teesta Barrage & River Reservoir",
    district: "Lalmonirhat",
    division: "Rangpur",
    tag: "River Megastructure",
    icon: "tree",
    rating: 4.6,
    reviews: "9.1K+",
    blurb: "Largest irrigation barrage in Bangladesh spanning the wild Teesta river.",
    image: "https://images.unsplash.com/photo-1509316975850-ff9c5deb0cd9?auto=format&fit=crop&w=800&q=80",
    facts: "Features 44 massive sluice gates holding back the mighty Teesta river flowing down from Sikkim.",
    lat: 26.1800,
    lon: 89.0500,
    travel: "Road",
    fareLabel: "Bus / Auto",
    fare: "৳60 – ৳150",
    season: "Oct – Apr",
    distance: "60 km",
    distanceFrom: "from Rangpur City",
    about: "The Teesta Barrage offers sweeping vistas over endless shimmering water channels. Visitors flock for fresh Bairali and Boal fish lunches by the lakeside.",
    gallery: [
      "https://images.unsplash.com/photo-1509316975850-ff9c5deb0cd9?auto=format&fit=crop&w=800&q=80",
      "images/places/kaptai.jpg",
      "images/places/ratargul.jpg"
    ]
  },
  {
    id: "chikli_park",
    name: "Chikli Water Park & Dighi",
    district: "Rangpur",
    division: "Rangpur",
    tag: "Urban Waterfront",
    icon: "tree",
    rating: 4.5,
    reviews: "8.7K+",
    blurb: "Sprawling lake recreational oasis with speedboats and night lights.",
    image: "images/places/kaptai.jpg",
    facts: "Historic water tank transformed into a modern eco-park with fountains and floating dining pavilions.",
    lat: 25.7450,
    lon: 89.2450,
    travel: "Road",
    fareLabel: "Rickshaw / Auto",
    fare: "৳30 – ৳60",
    season: "Year Round",
    distance: "4 km",
    distanceFrom: "from Rangpur Station",
    about: "A refreshing gathering spot in Rangpur. Rent pedal boats to drift across the serene lake, stroll along tree-lined promenades, and enjoy illuminated musical fountains in the evening.",
    gallery: ["images/places/kaptai.jpg", "images/places/ratargul.jpg", "images/places/srimangal.jpg"]
  },
  {
    id: "mirzapur_mosque",
    name: "Mirzapur Shahi Mosque",
    district: "Panchagarh",
    division: "Rangpur",
    tag: "Persian Domes",
    icon: "mosque",
    rating: 4.6,
    reviews: "4.3K+",
    blurb: "17th-century terracotta mosque built in Persian architectural style.",
    image: "images/places/bagerhat-2.jpg",
    facts: "Constructed during Emperor Shah Alam's reign with floral terracotta relief and ornate Persian calligraphy.",
    lat: 26.1700,
    lon: 88.5800,
    travel: "Road",
    fareLabel: "Auto Fare",
    fare: "৳40 – ৳100",
    season: "Year Round",
    distance: "18 km",
    distanceFrom: "from Atwari, Panchagarh",
    about: "An architectural surprise in the far north. Three beautiful domes, fluted corner minarets, and delicate terracotta vines display royal Mughal and Persian styling in quiet countryside.",
    gallery: ["images/places/bagerhat-2.jpg", "images/places/bagerhat.jpg", "images/places/lalbagh.jpg"]
  },
  {
    id: "chilarang_temple",
    name: "Chilarang Twin Temples",
    district: "Thakurgaon",
    division: "Rangpur",
    tag: "Stepped Shrines",
    icon: "landmark",
    rating: 4.5,
    reviews: "3.2K+",
    blurb: "Historic terracotta twin brick shrines dating to the late Mughal period.",
    image: "images/places/paharpur-4.jpg",
    facts: "Unique octagonal stepped base structures with intricate terracotta deities and floral panels.",
    lat: 26.0400,
    lon: 88.4700,
    travel: "Road",
    fareLabel: "Auto / Rickshaw",
    fare: "৳30 – ৳80",
    season: "Oct – Mar",
    distance: "6 km",
    distanceFrom: "from Thakurgaon town",
    about: "A tranquil historical site nestled in rural Thakurgaon. Two historic brick shrines stand side by side, showcasing surviving terracotta panels depicting folk life of 18th-century Bengal.",
    gallery: ["images/places/paharpur-4.jpg", "images/places/sonargaon.jpg", "images/places/lalbagh.jpg"]
  },
  {
    id: "sonar_char",
    name: "Sonar Char Beach",
    district: "Patuakhali",
    division: "Barishal",
    tag: "Untouched Golden Sands",
    icon: "beach",
    rating: 4.7,
    reviews: "4.2K+",
    blurb: "Untouched golden beach and forest island in the Bay of Bengal.",
    image: "images/places/coxsbazar-2.jpg",
    facts: "A pristine 10-km golden sandy beach surrounded by deep mangrove forests where red crabs paint the shore.",
    lat: 21.8800,
    lon: 90.5200,
    travel: "Water",
    fareLabel: "Trawler from Galachipa",
    fare: "৳400 – ৳800",
    season: "Nov – Mar",
    distance: "Offshore Island",
    distanceFrom: "from Rangabali / Kuakata",
    about: "Known as the golden beach for its radiant sands. Millions of red ghost crabs scurry across the wide tide flats, and you can walk for hours without seeing a single modern structure.",
    gallery: ["images/places/coxsbazar-2.jpg", "images/places/inani.jpg", "images/places/sundarbans.jpg"]
  },
  {
    id: "fatra_char",
    name: "Fatrar Char Mangrove",
    district: "Patuakhali",
    division: "Barishal",
    tag: "Sundarbans Extension",
    icon: "tree",
    rating: 4.6,
    reviews: "5.8K+",
    blurb: "Part of the Sundarbans mangrove forest accessible from Kuakata.",
    image: "images/places/sundarbans-3.jpg",
    facts: "Separated from Kuakata by river Andharmanik; home to wild boars, monkey troops, and breathing pneumatophores.",
    lat: 21.8400,
    lon: 90.0800,
    travel: "Water",
    fareLabel: "Trawler Boat",
    fare: "৳300 – ৳600",
    season: "Oct – Apr",
    distance: "10 km boat",
    distanceFrom: "from Kuakata Beach",
    about: "A thrilling mini-safari from Kuakata. Ride an engine trawler through narrow tidal canals to reach dense mangrove jungles where breathing roots thrust up from silky tidal mud.",
    gallery: ["images/places/sundarbans-3.jpg", "images/places/sundarbans.jpg", "images/places/coxsbazar.jpg"]
  },
  {
    id: "gangamati",
    name: "Gangamati Reserved Forest",
    district: "Patuakhali",
    division: "Barishal",
    tag: "Lagoon & Forest",
    icon: "beach",
    rating: 4.6,
    reviews: "6.1K+",
    blurb: "Coastal mangrove canal and prime sunrise spot east of Kuakata.",
    image: "images/places/coxsbazar-3.jpg",
    facts: "Where Gangamati canal flows into the Bay of Bengal, creating a scenic lagoon filled with red crabs and waterbirds.",
    lat: 21.8200,
    lon: 90.1800,
    travel: "Road",
    fareLabel: "Motorbike Ride",
    fare: "৳150 – ৳300",
    season: "Oct – Mar",
    distance: "7 km",
    distanceFrom: "from Kuakata Zero Point",
    about: "The ultimate sunrise adventure. Hire a local beach motorcycle to zoom along the damp sand at dawn to Gangamati canal, where glowing red sunrises illuminate mangrove roots.",
    gallery: ["images/places/coxsbazar-3.jpg", "images/places/inani.jpg", "images/places/himchari.jpg"]
  },
  {
    id: "swarupkathi",
    name: "Swarupkathi Floating Timber Market",
    district: "Pirojpur",
    division: "Barishal",
    tag: "Waterways & Timber",
    icon: "tree",
    rating: 4.6,
    reviews: "4.9K+",
    blurb: "Gigantic floating logs and timber rafts traded along canal networks.",
    image: "images/places/ratargul-2.jpg",
    facts: "Largest timber market in Bangladesh where millions of massive timber trunks float tied into river trains.",
    lat: 22.7500,
    lon: 90.1100,
    travel: "Water",
    fareLabel: "Engine Boat",
    fare: "৳400 – ৳900",
    season: "Year Round",
    distance: "25 km",
    distanceFrom: "from Barishal / Pirojpur",
    about: "An astonishing sight of riverine commerce. Entire river stretches are blanketed by floating logs of Sundari, Mehgani, and teak trees, with agile lumberjacks running across wet floating logs.",
    gallery: ["images/places/ratargul-2.jpg", "images/places/ratargul.jpg", "images/places/jaflong.jpg"]
  },
  {
    id: "durgasagar",
    name: "Durga Sagar Dighi",
    district: "Barishal",
    division: "Barishal",
    tag: "Historic Island Dighi",
    icon: "tree",
    rating: 4.5,
    reviews: "6.7K+",
    blurb: "Massive 1780 AD historic dighi with an emerald forested island.",
    image: "images/places/kaptai.jpg",
    facts: "Excavated by Raja Joy Narayan to alleviate drought; features a lush sanctuary island in the center where deer roam.",
    lat: 22.7600,
    lon: 90.2800,
    travel: "Road",
    fareLabel: "Auto Fare",
    fare: "৳40 – ৳90",
    season: "Year Round",
    distance: "12 km",
    distanceFrom: "from Barishal City",
    about: "A serene lake sanctuary. Walk along the 1.5-kilometer forested perimeter embankment, watch wild deer graze on the central island, and observe thousands of migratory pelicans in winter.",
    gallery: ["images/places/kaptai.jpg", "images/places/ratargul.jpg", "images/places/srimangal.jpg"]
  },
  {
    id: "char_kukri",
    name: "Char Kukri Mukri Wildlife Reserve",
    district: "Bhola",
    division: "Barishal",
    tag: "Mangrove Wildlife Island",
    icon: "tree",
    rating: 4.7,
    reviews: "4.5K+",
    blurb: "Remote southernmost island sanctuary teeming with deer and birds.",
    image: "images/places/sundarbans-4.jpg",
    facts: "Established as a wildlife sanctuary in 1981; renowned for keora forests, spotted deer, and Tarua virgin beach.",
    lat: 21.9200,
    lon: 90.6500,
    travel: "Water",
    fareLabel: "Trawler / Launch",
    fare: "৳500 – ৳1,200",
    season: "Nov – Mar",
    distance: "Deep Estuary",
    distanceFrom: "from Char Fasson, Bhola",
    about: "One of the most remote, pristine wildlife havens in southern Bangladesh. Roam through wild keora and golpata groves to find tranquil beaches facing the open Bay of Bengal.",
    gallery: ["images/places/sundarbans-4.jpg", "images/places/sundarbans.jpg", "images/places/inani.jpg"]
  },
  {
    id: "gokul_medh",
    name: "Gokul Medh (Behular Basor Ghar)",
    district: "Bogra",
    division: "Rajshahi",
    tag: "Mythological Citadel",
    icon: "landmark",
    rating: 4.6,
    reviews: "8.3K+",
    blurb: "Terraced stupa monument tied to the Manasa Mangal epic.",
    image: "images/places/paharpur.jpg",
    facts: "Features 172 rectangular blind cells arranged in tiers; folklore holds it as the bridal chamber of Behula and Lakhindar.",
    lat: 24.9300,
    lon: 89.3500,
    travel: "Road",
    fareLabel: "Auto Rickshaw",
    fare: "৳30 – ৳70",
    season: "Year Round",
    distance: "10 km",
    distanceFrom: "from Bogra City",
    about: "A striking archaeological relic from the 6th to 7th century. Climb the high stepped brick tiers to marvel at ancient structural engineering linked to Bengal's immortal folklore.",
    gallery: ["images/places/paharpur.jpg", "images/places/paharpur-2.jpg", "images/places/sonargaon.jpg"]
  },
  {
    id: "rani_bhabani",
    name: "Rani Bhabani Palace",
    district: "Natore",
    division: "Rajshahi",
    tag: "Queen's Palace",
    icon: "landmark",
    rating: 4.6,
    reviews: "9.8K+",
    blurb: "Palace of legendary 18th-century philanthropist Queen of Bengal.",
    image: "images/places/ahsanmanzil-3.jpg",
    facts: "Rani Bhabani managed a zamindari generating 70 lakh rupees in annual revenue, famed for building hundreds of schools and temples.",
    lat: 24.4100,
    lon: 88.9900,
    travel: "Road",
    fareLabel: "Rickshaw / Auto",
    fare: "৳20 – ৳50",
    season: "Year Round",
    distance: "Central",
    distanceFrom: "in Natore town",
    about: "The historic seat of 'Natore Rajbari'. Surrounded by defensive water moats and shaded banyan trees, the complex houses ornate terracotta Shiva temples and historic administrative courts.",
    gallery: ["images/places/ahsanmanzil-3.jpg", "images/places/sonargaon.jpg", "images/places/lalbagh.jpg"]
  },
  {
    id: "hardinge_bridge",
    name: "Hardinge & Lalon Shah Bridges",
    district: "Pabna",
    division: "Rajshahi",
    tag: "Historic Steel Bridges",
    icon: "landmark",
    rating: 4.7,
    reviews: "15K+",
    blurb: "1912 British steel railway bridge over the swirling Padma River.",
    image: "https://images.unsplash.com/photo-1509316975850-ff9c5deb0cd9?auto=format&fit=crop&w=800&q=80",
    facts: "Constructed with 16 massive steel spans over 1.8 km; survived intense aerial bombardment during the 1971 Liberation War.",
    lat: 24.0700,
    lon: 89.0300,
    travel: "Rail",
    fareLabel: "Train / Auto",
    fare: "৳40 – ৳100",
    season: "Year Round",
    distance: "Paksey",
    distanceFrom: "near Ishwardi, Pabna",
    about: "A triumph of industrial railway heritage. Stand on the Paksey riverside embankment as classic steam-era steel trusses echo with passing express trains crossing the mighty Padma.",
    gallery: [
      "https://images.unsplash.com/photo-1509316975850-ff9c5deb0cd9?auto=format&fit=crop&w=800&q=80",
      "images/places/sonargaon.jpg",
      "images/places/coxsbazar.jpg"
    ]
  },
  {
    id: "varendra_museum",
    name: "Varendra Research Museum",
    district: "Rajshahi",
    division: "Rajshahi",
    tag: "Oldest Museum in BD",
    icon: "landmark",
    rating: 4.7,
    reviews: "8.1K+",
    blurb: "Founded in 1910 — premier repository of Buddhist and Hindu stone sculptures.",
    image: "images/places/paharpur-3.jpg",
    facts: "Houses thousands of black stone sculptures from the Pala and Sena dynasties, and rare ancient palm-leaf manuscripts.",
    lat: 24.3650,
    lon: 88.6000,
    travel: "Road",
    fareLabel: "Rickshaw / Walking",
    fare: "৳20 – ৳50",
    season: "Year Round",
    distance: "Central",
    distanceFrom: "in Rajshahi City",
    about: "A treasure house of Bengali antiquity. The red-brick Indo-Saracenic building holds mesmerizing masterpieces of stone sculpture, from serene Avalokiteshvara icons to dynamic bronze Natarajas.",
    gallery: ["images/places/paharpur-3.jpg", "images/places/paharpur.jpg", "images/places/sonargaon.jpg"]
  },
  {
    id: "padma_char",
    name: "Padma River Char & Sunset",
    district: "Rajshahi",
    division: "Rajshahi",
    tag: "River Sunset Beach",
    icon: "tree",
    rating: 4.8,
    reviews: "16K+",
    blurb: "Golden sandbars and fiery sunsets along the Rajshahi riverfront.",
    image: "images/places/coxsbazar-4.jpg",
    facts: "In dry season, the Padma reveals miles of white sand dunes, offering camel rides and grilled fish by the waters.",
    lat: 24.3600,
    lon: 88.5900,
    travel: "Water",
    fareLabel: "Catamaran / Boat",
    fare: "৳100 – ৳300",
    season: "Oct – May",
    distance: "Central",
    distanceFrom: "from T-Bandh, Rajshahi",
    about: "Rajshahi's beloved evening promenade. Take a boat to the vast Padma island char, feel the fine white sand under your feet, and watch the crimson sun sink into the vast waters.",
    gallery: ["images/places/coxsbazar-4.jpg", "images/places/inani.jpg", "images/places/himchari.jpg"]
  },
  {
    id: "bau_botanical",
    name: "BAU Botanical Garden",
    district: "Mymensingh",
    division: "Mymensingh",
    tag: "Botanical Riverside Haven",
    icon: "tree",
    rating: 4.7,
    reviews: "9.3K+",
    blurb: "Historic botanical reserve along the Old Brahmaputra river.",
    image: "images/places/srimangal-2.jpg",
    facts: "Houses over 600 rare plant species, ancient lotus ponds, fossil wood exhibits, and bamboo groves.",
    lat: 24.7200,
    lon: 90.4300,
    travel: "Road",
    fareLabel: "Rickshaw / Auto",
    fare: "৳30 – ৳70",
    season: "Year Round",
    distance: "5 km",
    distanceFrom: "from Mymensingh Sadar",
    about: "An idyllic botanical sanctuary stretching alongside the gentle Brahmaputra. Shaded canopy avenues, exotic orchids, and wooden benches create the ideal retreat for nature lovers.",
    gallery: ["images/places/srimangal-2.jpg", "images/places/srimangal.jpg", "images/places/ratargul.jpg"]
  },
  {
    id: "madhutila",
    name: "Madhutila Eco Park",
    district: "Sherpur",
    division: "Mymensingh",
    tag: "Garo Foothill Wilderness",
    icon: "mountain",
    rating: 4.5,
    reviews: "6.4K+",
    blurb: "Pristine forest ridges bordering Meghalaya with watchtower views.",
    image: "images/places/sajek-3.jpg",
    facts: "Features a natural water reservoir, star observation bridge, and an active corridor for wild Asian elephants.",
    lat: 25.2100,
    lon: 90.2200,
    travel: "Road",
    fareLabel: "Bus / Auto",
    fare: "৳150 – ৳350",
    season: "Oct – Mar",
    distance: "35 km",
    distanceFrom: "from Sherpur town",
    about: "Where the plains rise into emerald mountain ridges. Climb the central watchtower for sweeping views of Indian hills, cross hanging bridges over placid waters, and breathe crisp mountain air.",
    gallery: ["images/places/sajek-3.jpg", "images/places/sajek.jpg", "images/places/himchari.jpg"]
  },
  {
    id: "madhupur_forest",
    name: "Madhupur National Sal Forest",
    district: "Tangail",
    division: "Dhaka",
    tag: "Red Soil Sal Forest",
    icon: "tree",
    rating: 4.6,
    reviews: "8.1K+",
    blurb: "Historic high sal forest with indigenous Mandi tribal culture.",
    image: "images/places/srimangal-4.jpg",
    facts: "Ancient red clay terraces covered in tall Shorea robusta trees; famous for luscious local pineapples and ginger.",
    lat: 24.6200,
    lon: 90.0300,
    travel: "Road",
    fareLabel: "Bus Fare",
    fare: "৳120 – ৳250",
    season: "Oct – Apr",
    distance: "125 km",
    distanceFrom: "from Mohakhali, Dhaka",
    about: "A forest rich in ecology and indigenous culture. Shaded canopy walks among towering sal trunks lead to indigenous Garo villages renowned for hospitality and juicy honey queen pineapples.",
    gallery: ["images/places/srimangal-4.jpg", "images/places/srimangal.jpg", "images/places/ratargul.jpg"]
  },
  {
    id: "sagordari",
    name: "Sagordari Michael Madhusudan House",
    district: "Jashore",
    division: "Khulna",
    tag: "Literary Shrine",
    icon: "landmark",
    rating: 4.6,
    reviews: "7.7K+",
    blurb: "Birthplace of epic poet Michael Madhusudan on the Kobodak river.",
    image: "images/places/sonargaon-3.jpg",
    facts: "The poetic setting for immortal verses dedicated to River Kobodak ('Satata, he nodi, tumi poro mor mone').",
    lat: 22.9100,
    lon: 89.1800,
    travel: "Road",
    fareLabel: "Bus / Auto",
    fare: "৳60 – ৳150",
    season: "Year Round",
    distance: "45 km",
    distanceFrom: "from Jashore City",
    about: "A romantic riverine estate. The mango orchards slope gently down to the shimmering Kobodak river, where literary pilgrims gather to pay homage to the pioneer of modern Bengali poetry.",
    gallery: ["images/places/sonargaon-3.jpg", "images/places/sonargaon.jpg", "images/places/ahsanmanzil.jpg"]
  },
  {
    id: "tungipara",
    name: "Tungipara Heritage Complex",
    district: "Gopalganj",
    division: "Dhaka",
    tag: "National Memorial",
    icon: "landmark",
    rating: 4.8,
    reviews: "19K+",
    blurb: "Mausoleum complex of the Father of the Nation Bangabandhu.",
    image: "https://images.unsplash.com/photo-1599707367072-cd6ada2bc375?auto=format&fit=crop&w=800&q=80",
    facts: "A serene red ceramic-brick and Greek marble architectural monument surrounded by peaceful canal waterways.",
    lat: 22.9000,
    lon: 89.9000,
    travel: "Road",
    fareLabel: "Express Bus",
    fare: "৳250 – ৳500",
    season: "Year Round",
    distance: "160 km",
    distanceFrom: "from Dhaka (via Padma Bridge)",
    about: "A solemn and beautifully kept national landmark. Set on the banks of the Baigar river with pristine green lawns, lotus ponds, and white marble arches honoring Bangabandhu Sheikh Mujibur Rahman.",
    gallery: [
      "https://images.unsplash.com/photo-1599707367072-cd6ada2bc375?auto=format&fit=crop&w=800&q=80",
      "images/places/lalbagh.jpg",
      "images/places/ahsanmanzil.jpg"
    ]
  },
  {
    id: "chhatak",
    name: "Chhatak Lime Hills & Surma Valley",
    district: "Sunamganj",
    division: "Sylhet",
    tag: "River Gateway",
    icon: "mountain",
    rating: 4.5,
    reviews: "3.9K+",
    blurb: "Surma river valley with aerial ropeway and views of Meghalaya.",
    image: "images/places/jaflong-4.jpg",
    facts: "Home to the historic 19-km aerial ropeway transporting limestone across the international border.",
    lat: 25.0400,
    lon: 91.6700,
    travel: "Rail",
    fareLabel: "Train / Bus",
    fare: "৳50 – ৳120",
    season: "Oct – Apr",
    distance: "32 km",
    distanceFrom: "from Sylhet City",
    about: "A scenic junction where the Surma river widens into tranquil waters framed by distant Khasi hills. Watch vintage ropeway buckets carry lime across the valley.",
    gallery: ["images/places/jaflong-4.jpg", "images/places/jaflong.jpg", "images/places/ratargul.jpg"]
  },
  {
    id: "suhrawardy_udyan",
    name: "Suhrawardy Udyan & Glass Tower",
    district: "Dhaka",
    division: "Dhaka",
    tag: "Historic Park",
    icon: "landmark",
    rating: 4.7,
    reviews: "21K+",
    blurb: "150 ft illuminated glass Tower of Light and historic March 7 podium.",
    image: "images/places/lalbagh-3.jpg",
    facts: "The historic site where the 7th March 1971 speech was delivered and where the Pakistani surrender took place.",
    lat: 23.7333,
    lon: 90.3980,
    travel: "Road",
    fareLabel: "Metro (TSC Station)",
    fare: "৳20 – ৳40",
    season: "Year Round",
    distance: "Central",
    distanceFrom: "at Dhaka University Campus",
    about: "A sacred park in the heart of Dhaka. Features an eternal flame ('Shikha Chirantan'), an underground Liberation War museum, and a towering glass monument that glows against the night sky.",
    gallery: ["images/places/lalbagh-3.jpg", "images/places/lalbagh.jpg", "images/places/ahsanmanzil.jpg"]
  },
  {
    id: "khanjahan_tomb",
    name: "Tomb of Khan Jahan Ali",
    district: "Bagerhat",
    division: "Khulna",
    tag: "Sufi Heritage",
    icon: "mosque",
    rating: 4.8,
    reviews: "14K+",
    blurb: "1459 AD Sufi saint tomb beside a sacred lake with marsh crocodiles.",
    image: "images/places/bagerhat.jpg",
    facts: "The vast Thakur Dighi lake contains friendly marsh crocodiles named 'Kalapahar' and 'Dholapahar' responding to keepers' calls.",
    lat: 22.6600,
    lon: 89.7900,
    travel: "Road",
    fareLabel: "Auto Rickshaw",
    fare: "৳30 – ৳60",
    season: "Year Round",
    distance: "4 km",
    distanceFrom: "from Sixty Dome Mosque",
    about: "A place of profound peace. Walk down wide stone steps to the ancient lake as breezes rustle through banyan trees, while pilgrims gather at the single-domed brick mausoleum.",
    gallery: ["images/places/bagerhat.jpg", "images/places/bagerhat-2.jpg", "images/places/bagerhat-3.jpg"]
  }
];

const existingIds = new Set(currentData.places.map(p => p.id));
MORE_PLACES.forEach(p => {
  if (!existingIds.has(p.id)) {
    currentData.places.push(p);
    existingIds.add(p.id);
  }
});

fs.writeFileSync(placesPath, JSON.stringify(currentData, null, 2), 'utf8');
console.log(`Current place count in places.json: ${currentData.places.length}`);
